### ISSUE TITLE
Renamed nodes are forgotten

### ISSUE THREAD

**Issue by mdavids** [SIDN/spin#1]
Even though the rename is still present in /tmp/spin_userdata.cfg, it does not show up in the SPIN traffic monitor after a while. Renaming it again fixes the problem temporarily. Also, refreshing the screen fixes it.

**Comment by tjeb** [comment]
I think the recent changes might accidentally have fixed this (though they probably introduced other issues); info about renamed nodes is now passed directly with the node information

**Comment by mdavids** [comment]
Seems fixed in beta-2017-07-10-1711 but needs some more testing.

**Comment by ElmerLastdrager** [comment]
Can't reproduce anymore, so considering this one fixed.
