### ISSUE TITLE
Traffic only shows when using NAT

### ISSUE THREAD

**Issue by frankvandenhurk** [SIDN/spin#11]
Is it possible to show the traffic that flows between two bridges interfaces? I would like to put SPIN between het router and the network with the IoT devices, like a trasparant man-in-the-middle device, without an extra NAT.

**Comment by tjeb** [comment]
currently this is not supported, but it is definitely a good idea. I'll look into it.

**Comment by ElmerLastdrager** [comment]
We have put this on the list of good ideas for the longer term. I'm closing this issue.
