### ISSUE TITLE
Incorrect visualisation of node

### ISSUE THREAD

**Issue by ElmerLastdrager** [SIDN/spin#13]
Occasionally, a node will wrongfully group ip's into a single cluster. This occurs for the visualisation only (not the actual blocking).

Reproduce:
Note: Use a 'fresh' (just restarted) device

```
dig example.nl
curl example.nl >/dev/null
```
Then, block example.nl in the visualisation. Followed by:
```
curl example.nl >/dev/null (to confirm it is blocked)
dig valibox.sidnlabs.nl
curl valibox.sidnlabs.nl >/dev/null
curl sidnlabs.nl >/dev/null
dig valibox.
```
Result:
The new group contains "valibox.,example.nl.,valibox.sidnlabs.nl.,servfail.sidnlabs.nl."

example.nl and valibox.sidnlabs.nl are correctly merged (same ip). "valibox." should not be merged into the same group. "Valibox." is still accessible.

**Comment by tjeb** [comment]
Can you please check if this is still an issue? I can't seem to reproduce it.

**Comment by ElmerLastdrager** [comment]
Unable to reproduce at the latest beta-version.
