### ISSUE TITLE
Aggregation of packets is too lazy

### ISSUE THREAD

**Issue by ElmerLastdrager** [SIDN/spin#14]
spind aggregates packets in a loop. When there is no further traffic, the latest set of packets is not transmitted to the client, or is transmitted with great delay.

**Comment by ElmerLastdrager** [comment]
@tjeb is this fixed by now?

**Comment by tjeb** [comment]
I believe this was fixed in 8cdf035f82abcb848f7b2bda313bb0f1093c16fc If not, please reopen this issue.
