### ISSUE TITLE
No change log when on latest version

### ISSUE THREAD

**Issue by mdavids** [SIDN/spin#24]
http://valibox./autonta/update_check only shows a change log when there is a new version. When the latest version is already installed, it just show that, without any change log.

Bug or a feature?

**Comment by tjeb** [comment]
It was intentional, but with the changelog growing in size, it needs addressing anyway.

Fixed in SIDN/sidn_openwrt_pkgs@1f998c363fd5f11c698c15a340494c2071ecb2b9
