### ISSUE TITLE
Valibox interface broken when using IP

### ISSUE THREAD

**Issue by ElmerLastdrager** [SIDN/spin#32]
The Valibox (including SPIN) interface does not work properly when you connect to the device's ip address directly. It only works when you connect to "valibox."

Expected result: having proper functionality when browsing to the ip-address of the valibox.

**Comment by tjeb** [comment]
This was an nginx config issue; Should be fixed in SIDN/valibox-spin-builder@b9ff8a6cf864e79bf782d2d5459f6ab50b82d5c1
