### ISSUE TITLE
Node incorrectly hidden

### ISSUE THREAD

**Issue by ElmerLastdrager** [SIDN/spin#34]
Weird bug, I do a DNS query and the node (RPi) is suddenly hidden (after 1 second or so).
Need more time to reproduce.

![screen shot 2018-02-27 at 09 58 58](https://user-images.githubusercontent.com/1679693/36719297-f7e7fc9c-1ba4-11e8-8bd5-7637791a0499.png)

**Comment by ElmerLastdrager** [comment]
@tjeb this is your area. The DNS query information received over MQTT includes the wrong timestamp. As in, the 'lastseen' property does not get updated when the node sends a DNS query.

**Comment by ElmerLastdrager** [comment]
Steps to reproduce:
`$ curl example.nl >/dev/null`
wait 601 seconds
`$ dig example.nl >/dev/null`
Observe that the device-node gets removed at the next call to `cleanNetwork()`.

**Comment by tjeb** [comment]
IT was a client-side error; the 'from' node was updated, but with the old value, instead of the new. Should be fixed in a66b09be4d460549b6df8897512f0b76febcfcda (also for blocked packets)
