### ISSUE TITLE
Should we allow nginx to log?

### ISSUE THREAD

**Issue by mdavids** [SIDN/spin#4]
Maybe disable logging in standard-situation and just enable it while debugging.

**Comment by ElmerLastdrager** [comment]
Maybe we can provide an option to log to console (like spin_print), not to disk.

**Comment by ElmerLastdrager** [comment]
Made a pull request to disable logging. For debugging, it can be manually enabled again.

**Comment by ElmerLastdrager** [comment]
Check option to use syslog.
