### ISSUE TITLE
Build fails on core2pubsub.c, fix suggestion included

### ISSUE THREAD

**Issue by ExploWare** [SIDN/spin#77]
Following all steps as in the Linux (PC) steps, on a fresh Armbian 21.05.2 Focal with Linux 5.10.34-sunxi  
make throws an error
../../spind/core2pubsub.c:198:5: error: ignoring return value of ‘mkstemp’, declared with attribute warn_unused_result [-Werror=unused-result]

Line 198 of core2pubsub.c is
    mkstemp(mosq_conf_filename);
I get the build working when I prefix that line
    (void)!mkstemp(mosq_conf_filename);

Since I'm no experienced coder in C, I don't know if this actually is a correct way of solving though :)

**Comment by cschutijser** [comment]
Hi, I committed a different fix, see https://github.com/SIDN/spin/commit/16773b470e394f82661ec1c00234a7da96dc9373. Thanks for noticing and telling us!

**Comment by ExploWare** [comment]
Confirmed, with pleasure
