### ISSUE TITLE
dependency missing and a wrong instruction

### ISSUE THREAD

**Issue by ExploWare** [SIDN/spin#78]
in the installation steps for Linux (PC) there should be mention of the requirement for ipset to be able to function as expected. 
At least in my installation on Armbian it was needed to add.
Further down in the Running section, there is a command to be executed: `(cd ./src/build/spind/; spind-o -d)`, that fails because it misses the ./ before the executable.

**Comment by cschutijser** [comment]
> in the installation steps for Linux (PC) there should be mention of the requirement for ipset to be able to function as expected.
> At least in my installation on Armbian it was needed to add.

Just to make sure I understand you correctly, can you be a little bit more specific? Do you mean that you had to install another package and the name of that package was "ipset"?

> Further down in the Running section, there is a command to be executed: `(cd ./src/build/spind/; spind-o -d)`, that fails because it misses the ./ before the executable.

Good point. I'll fix that once I know what to do about ipset.

**Comment by ExploWare** [comment]
> 
> 
> > in the installation steps for Linux (PC) there should be mention of the requirement for ipset to be able to function as expected.
> > At least in my installation on Armbian it was needed to add.
> 
> Just to make sure I understand you correctly, can you be a little bit more specific? Do you mean that you had to install another package and the name of that package was "ipset"?
Indeed that is the case:
Context: I started `spind` and `spinweb` without any trouble but the webpage showed a red 'Not Connected' status. A line in the output was telling me it could not run ipset.
once I ran `apt install ipset` and then restarted the two applications it got Connected
> 
> > Further down in the Running section, there is a command to be executed: `(cd ./src/build/spind/; spind-o -d)`, that fails because it misses the ./ before the executable.
> 
> Good point. I'll fix that once I know what to do about ipset.

Great, thanks.
I noticed make install is also a possibility, as for most build scripts, but it might be worth to mention also.

**Comment by cschutijser** [comment]
> > > in the installation steps for Linux (PC) there should be mention of the requirement for ipset to be able to function as expected.
> > > At least in my installation on Armbian it was needed to add.
> > 
> > 
> > Just to make sure I understand you correctly, can you be a little bit more specific? Do you mean that you had to install another package and the name of that package was "ipset"?
> 
> Indeed that is the case:
> Context: I started `spind` and `spinweb` without any trouble but the webpage showed a red 'Not Connected' status. A line in the output was telling me it could not run ipset.
> once I ran `apt install ipset` and then restarted the two applications it got Connected
> My system: `Armbian 21.05.2 Focal with Linux 5.10.34-sunxi` on a `Nanopi Neo Air`

Alright, makes sense. I see that the ipset package is also available on "regular" Debian so I've added ipset to the list of runtime dependencies, see https://github.com/SIDN/spin/commit/95087a5969cb7ea34e6b282c6ff5f1a0f438444a.

> > > Further down in the Running section, there is a command to be executed: `(cd ./src/build/spind/; spind-o -d)`, that fails because it misses the ./ before the executable.
> > 
> > 
> > Good point. I'll fix that once I know what to do about ipset.
> 
> Great, thanks.

I've now adjusted that too in the previously mentioned commit.

> I noticed make install is also a possibility, as for most build scripts, but it might be worth to mention also.

I'll think about that some more.

Thanks for your feedback!
