### ISSUE TITLE
Spinweb MQTT config

### ISSUE THREAD

**Issue by ExploWare** [SIDN/spin#80]
Should SPINWEB to run on another device than the SPIND ?

I am not able to define an external MQTT broker for spinweb in the config files. (I noticed I can add it in the query string)
But when I compile and run SPINWEB in the big server I have available, which is also running MQTT (with login credentials) I notice the webpage keeps on popping up the login window. 
Tested from laptop but also from the same host as the spinweb and mqtt are running on.
I can connect to the same system through mosquitto_sub cli tool, as well as other applications from remote (over mqttS), lan and localhost.
Another issue I expect to run into is the definition of the mqtt channels to read from. SPIN/commands would be very useful to allow to be dynamic, PI4/SPIN/commands for example.

When I installed the whole SPIN on a single-board-computer it worked fine.

**Comment by tjeb** [comment]
The password isn't set correctly, resulting in the prompt being shown again, should be fixed in commit a668b665f8d1dc52a5f047380b47db1c5c88d548
