### ISSUE TITLE
Error: cannot specify both an extsrc listen address and socket path

### ISSUE THREAD

**Issue by frankvandenhurk** [SIDN/spin#87]
What I am trying to accomplish:

- Run spin-pcap-reader with -i on my router (Unifi Dream Machine Pro)
- Have spind and spinweb running on another machine and receive info from spin-pcap-reader over the network
 

But when I try to start spind to listen to messages from an exteral source (my router):

```
sudo ~/spin/src/build/spind/spind -doP -E <OWN IP>
Error: cannot specify both an extsrc listen address and socket path

```

Problem is that I haven't configured a local socket path. Is it possible it uses a hardcoded socket path that conflicts with the -E option? Or am I doing something wrong?

**Comment by frankvandenhurk** [comment]
Commented out the check in spind.c:

```
//    if (extsrc_listen_addr && extsrc_socket_path) {
//       fprintf(stderr, "Error: cannot specify both an extsrc listen address and socket path\n");
//        print_help();
//        exit(1);
//    }

```

recompiled, and now I have a working setup!

I am running multiple spin-pcap-reader's on my router (one for each client VLAN), sending their data over the network to a spind running on another machine. Really nice, I love this tool!

For everyone who has a Unifi Dream Machine Pro and wants to run the spin-pcap-reader on it: I compiled it on a Raspberry running a 64-bit OS (to prevent the issues you run into when you start cross compiling) and copied spin-pcap-reader to the UDM Pro. You also have to copy libcrypto.so.1.1, libldns.so.3, libpcap.so.0.8 and libssl.so.1.1 to /usr/lib on the UDM Pro.

**Comment by frankvandenhurk** [comment]
Yes! No build error's and working -E option.

**Comment by cschutijser** [comment]
The commit is now on the master branch, thanks for your confirmation.
